// Release/manifest sanity checks: version parity, required files present,
// the 500 LOC-per-file cap, and no leftover AI-assistance branding.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const EXCLUDED_DIRS = new Set(['.git', 'node_modules', 'zips', 'tests']);
const LOC_CAP = 500;

const FORBIDDEN_PATTERNS = [
  /\bclaude\b/i,
  /\bchatgpt\b/i,
  /\bcopilot\b/i,
  /\banthropic\b/i,
  /\bopenai\b/i,
  /ai-assisted/i,
  /generated by ai/i
];

function collectJsFiles(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue;
      files.push(...collectJsFiles(path.join(dir, entry.name)));
    } else if (/\.(js|mjs)$/.test(entry.name)) {
      files.push(path.join(dir, entry.name));
    }
  }
  return files;
}

function validateModule() {
  const errors = [];

  const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8'));
  const moduleJson = JSON.parse(fs.readFileSync(path.join(projectRoot, 'module.json'), 'utf8'));

  if (packageJson.version !== moduleJson.version) {
    errors.push(`Version mismatch: package.json (${packageJson.version}) vs module.json (${moduleJson.version})`);
  }

  const requiredFiles = [
    'package.json',
    'module.json',
    'LICENSE',
    'README.md',
    'CHANGELOG.md',
    'main.js',
    'src/LDTriggerz.js',
    'src/hooks.js',
    'src/constants.js',
    'src/TriggerEngine.js',
    'src/ConditionAdapter.js',
    'src/DataManager.js',
    'src/SocketHandler.js',
    'src/UIManager.js',
    'src/MacroRunner.js',
    'src/Logger.js'
  ];

  for (const file of requiredFiles) {
    if (!fs.existsSync(path.join(projectRoot, file))) {
      errors.push(`Missing required file: ${file}`);
    }
  }

  const jsFiles = collectJsFiles(projectRoot);
  for (const file of jsFiles) {
    const lineCount = fs.readFileSync(file, 'utf8').split('\n').length;
    if (lineCount > LOC_CAP) {
      errors.push(`${path.relative(projectRoot, file)} exceeds the ${LOC_CAP} LOC cap (${lineCount} lines)`);
    }
  }

  const textExtensions = /\.(js|mjs|json|md)$/;
  const textFiles = [
    ...jsFiles,
    ...fs.readdirSync(projectRoot).filter((entry) => textExtensions.test(entry)).map((entry) => path.join(projectRoot, entry))
  ];
  for (const file of textFiles) {
    const content = fs.readFileSync(file, 'utf8');
    for (const pattern of FORBIDDEN_PATTERNS) {
      if (pattern.test(content)) {
        errors.push(`Found forbidden pattern ${pattern} in ${path.relative(projectRoot, file)}`);
      }
    }
  }

  if (errors.length > 0) {
    console.error('Validation failed:');
    errors.forEach((error) => console.error(`  - ${error}`));
    process.exit(1);
  }

  console.log(`Validation passed for ${packageJson.name} ${packageJson.version}`);
}

validateModule();
